#!/usr/bin/env bash
# Generate the four secret files compose.yaml mounts, once, into deploy/secrets/.
#
# It refuses to overwrite anything that already exists, and the reason is the
# custody secret: regenerating it does not reset a password, it makes every
# EBICS private key in the database permanently unreadable. There is no undo
# and no recovery except re-keying with each bank on paper.
#
#   PAINFREE_IMAGE=… deploy/init-secrets.sh
#
# The custody secret is generated by the image's own `new-secret` (a CSPRNG,
# 32 url-safe bytes) rather than by whatever is on the host.
set -euo pipefail

root=$(cd "$(dirname "$0")/.." && pwd)
secrets="$root/deploy/secrets"

engine=${ENGINE:-}
if [ -z "$engine" ]; then
    if command -v podman >/dev/null 2>&1; then engine=podman
    elif command -v docker >/dev/null 2>&1; then engine=docker
    else echo "no container engine: install podman or docker" >&2; exit 1; fi
fi

if [ -z "${PAINFREE_IMAGE:-}" ] && [ -f "$root/.env" ]; then
    PAINFREE_IMAGE=$(sed -n 's/^PAINFREE_IMAGE=//p' "$root/.env" | head -1)
fi
if [ -z "${PAINFREE_IMAGE:-}" ]; then
    echo "PAINFREE_IMAGE is not set: build the image first (deploy/build-image.sh)" >&2
    exit 1
fi

mkdir -p "$secrets"
chmod 700 "$secrets"

existing=()
for name in db_password database_url custody_secret oidc_client_secret; do
    [ -e "$secrets/$name" ] && existing+=("$name")
done
if [ ${#existing[@]} -gt 0 ]; then
    echo "refusing to overwrite existing secrets: ${existing[*]}" >&2
    echo >&2
    echo "deploy/secrets/custody_secret is the only copy of the key every stored" >&2
    echo "EBICS private key is sealed under. Replacing it does not reset it — it" >&2
    echo "orphans the database. To rotate deliberately, see the rotation section" >&2
    exit 1
fi

write() {
    umask 077
    printf '%s' "$2" > "$secrets/$1"
    # 0444, inside a 0700 directory. The directory is the protection: nothing
    # but this account can traverse it. The file itself has to be readable by
    # *other*, because compose bind-mounts it into a container that runs as an
    # unprivileged uid of its own -- a 0600 file owned by the host user is a
    # container that restart-loops on "Permission denied", which is how this
    # was found rather than assumed.
    chmod 444 "$secrets/$1"
}

# Both come from the image's own generator: a CSPRNG, url-safe characters, so
# the password can go into the database URL without escaping.
db_password=$("$engine" run --rm "$PAINFREE_IMAGE" new-secret)
custody_secret=$("$engine" run --rm "$PAINFREE_IMAGE" new-secret)

write db_password "$db_password"
write database_url "postgresql+psycopg://painfree:${db_password}@db:5432/painfree"
write custody_secret "$custody_secret"
# A placeholder: a public OIDC client using PKCE has no secret, but the file
# has to exist for the mount to succeed. Replace it with the provider's value
# if the client is confidential.
write oidc_client_secret "replace-with-the-oidc-client-secret-or-leave-unused"

cat >&2 <<'NOTE'
written: deploy/secrets/{db_password,database_url,custody_secret,oidc_client_secret}

Back up deploy/secrets/custody_secret NOW, somewhere that is not this host —
a password manager or a sealed envelope. It is not in the database, no database
backup contains it, and without it a restored database contains nothing but
unreadable ciphertext where the bank keys used to be.
NOTE
